
Procedure SamplePattern;
Begin
	PlayTable.Lines[0].YM1 := 0;
	PlayTable.Lines[0].Tempo := 250;
	PlayTable.Lines[0].Enabled := True;

	PlayTable.Lines[1].YM1 := 0;
	PlayTable.Lines[1].Tempo := 250;
	PlayTable.Lines[1].Enabled := True;

	PlayTable.Lines[2].YM1 := 1;
	PlayTable.Lines[2].Tempo := 500;
	PlayTable.Lines[2].Enabled := True;

	{ pat 0 }

	YMPatterns[0].Sequence[0].CT := 1;
	YMPatterns[0].Sequence[0].FT := 122;
	YMPatterns[0].Sequence[0].Enabled := True;

	YMPatterns[0].Sequence[1].CT := 1;
	YMPatterns[0].Sequence[1].FT := 81;
	YMPatterns[0].Sequence[1].Enabled := True;

	YMPatterns[0].Sequence[2].CT := 1;
	YMPatterns[0].Sequence[2].FT := 44;
	YMPatterns[0].Sequence[2].Enabled := True;

	YMPatterns[0].Sequence[3].CT := 1;
	YMPatterns[0].Sequence[3].FT := 27;
	YMPatterns[0].Sequence[3].Enabled := True;

	YMPatterns[0].Sequence[4].CT := 0;
	YMPatterns[0].Sequence[4].FT := 252;
	YMPatterns[0].Sequence[4].Enabled := True;

	YMPatterns[0].Sequence[5].CT := 0;
	YMPatterns[0].Sequence[5].FT := 225;
	YMPatterns[0].Sequence[5].Enabled := True;

	YMPatterns[0].Sequence[6].CT := 0;
	YMPatterns[0].Sequence[6].FT := 212;
	YMPatterns[0].Sequence[6].Enabled := True;

	YMPatterns[0].Sequence[0].CT := 1;
	YMPatterns[0].Sequence[0].FT := 122;
	YMPatterns[0].Sequence[0].Enabled := True;

	YMPatterns[0].Sequence[1].CT := 1;
	YMPatterns[0].Sequence[1].FT := 81;
	YMPatterns[0].Sequence[1].Enabled := True;

	YMPatterns[0].Sequence[2].CT := 1;
	YMPatterns[0].Sequence[2].FT := 44;
	YMPatterns[0].Sequence[2].Enabled := True;

	YMPatterns[0].Sequence[3].CT := 1;
	YMPatterns[0].Sequence[3].FT := 27;
	YMPatterns[0].Sequence[3].Enabled := True;

	YMPatterns[0].Sequence[4].CT := 0;
	YMPatterns[0].Sequence[4].FT := 252;
	YMPatterns[0].Sequence[4].Enabled := True;

	YMPatterns[0].Sequence[5].CT := 0;
	YMPatterns[0].Sequence[5].FT := 225;
	YMPatterns[0].Sequence[5].Enabled := True;

	YMPatterns[0].Sequence[6].CT := 0;
	YMPatterns[0].Sequence[6].FT := 212;
	YMPatterns[0].Sequence[6].Enabled := True;

	{ pat 1 }

	YMPatterns[1].Sequence[0].CT := 1;
	YMPatterns[1].Sequence[0].FT := 122;
	YMPatterns[1].Sequence[0].Enabled := True;

	YMPatterns[1].Sequence[1].CT := 1;
	YMPatterns[1].Sequence[1].FT := 81;
	YMPatterns[1].Sequence[1].Enabled := True;

	YMPatterns[1].Sequence[2].CT := 1;
	YMPatterns[1].Sequence[2].FT := 44;
	YMPatterns[1].Sequence[2].Enabled := True;

	YMPatterns[1].Sequence[3].CT := 1;
	YMPatterns[1].Sequence[3].FT := 27;
	YMPatterns[1].Sequence[3].Enabled := True;

	YMPatterns[1].Sequence[4].CT := 0;
	YMPatterns[1].Sequence[4].FT := 252;
	YMPatterns[1].Sequence[4].Enabled := True;

	YMPatterns[1].Sequence[5].CT := 0;
	YMPatterns[1].Sequence[5].FT := 225;
	YMPatterns[1].Sequence[5].Enabled := True;

	YMPatterns[1].Sequence[6].CT := 0;
	YMPatterns[1].Sequence[6].FT := 212;
	YMPatterns[1].Sequence[6].Enabled := True;

	YMPatterns[1].Sequence[0].CT := 1;
	YMPatterns[1].Sequence[0].FT := 122;
	YMPatterns[1].Sequence[0].Enabled := True;

	YMPatterns[1].Sequence[1].CT := 1;
	YMPatterns[1].Sequence[1].FT := 81;
	YMPatterns[1].Sequence[1].Enabled := True;

	YMPatterns[0].Sequence[2].CT := 1;
	YMPatterns[1].Sequence[2].FT := 44;
	YMPatterns[1].Sequence[2].Enabled := True;

	YMPatterns[1].Sequence[3].CT := 1;
	YMPatterns[1].Sequence[3].FT := 27;
	YMPatterns[1].Sequence[3].Enabled := True;

	YMPatterns[1].Sequence[4].CT := 0;
	YMPatterns[1].Sequence[4].FT := 252;
	YMPatterns[1].Sequence[4].Enabled := True;

	YMPatterns[1].Sequence[5].CT := 0;
	YMPatterns[1].Sequence[5].FT := 225;
	YMPatterns[1].Sequence[5].Enabled := True;

	YMPatterns[1].Sequence[6].CT := 0;
	YMPatterns[1].Sequence[6].FT := 212;
	YMPatterns[1].Sequence[6].Enabled := True;

	YMPatterns[1].Sequence[7].CT := 1;
	YMPatterns[1].Sequence[7].FT := 122;
	YMPatterns[1].Sequence[7].Enabled := True;

	YMPatterns[1].Sequence[8].CT := 1;
	YMPatterns[1].Sequence[8].FT := 81;
	YMPatterns[1].Sequence[8].Enabled := True;

	YMPatterns[1].Sequence[9].CT := 1;
	YMPatterns[1].Sequence[9].FT := 44;
	YMPatterns[1].Sequence[9].Enabled := True;

	YMPatterns[1].Sequence[10].CT := 1;
	YMPatterns[1].Sequence[10].FT := 27;
	YMPatterns[1].Sequence[10].Enabled := True;

	YMPatterns[1].Sequence[11].CT := 0;
	YMPatterns[1].Sequence[11].FT := 252;
	YMPatterns[1].Sequence[11].Enabled := True;

	YMPatterns[1].Sequence[12].CT := 0;
	YMPatterns[1].Sequence[12].FT := 225;
	YMPatterns[1].Sequence[12].Enabled := True;
End;
